### PR TITLE
Adjust GUI to fit precisely on my screen

### PR DESCRIPTION
**Pull request by eric-unc**
Basically just reducing negative space.
image

### CODE REVIEW

**Comment by jesse-wei** [comment]
Looks like this on mine (and I can't increase the window size since `MAX_RATIO` was changed).

image

I see that you also modified the `.ui` file. What happens on your screen if you change `MAX_RATIO` (width and height) back to 1 but keep the `.ui` file changes?

**Comment by eric-unc** [comment]
Then it's too big. The "Apply" button (which is the most important button) is hidden.
image

**Comment by jesse-wei** [comment]
It's weird that adjusting the max ratio adjusts the actual startup GUI size. It's surely possible to set a specific startup GUI size (and we'll want to base it on monitor dimensions), so we should look for how to do that.

I think max ratio should always be 1 since the user shouldn't be prevented from maximizing the app. (Actually, on my laptop, even if I click the green maximize button with max ratio < 1, the GUI still doesn't fill the whole screen and also just made my computer crash lol).

**Comment by eric-unc** [comment]
> I think max ratio should always be 1 since the user shouldn't be prevented from maximizing the app. (Actually, on my laptop, even if I click the green maximize button with max ratio < 1, the GUI still doesn't fill the whole screen and also just made my computer crash lol).

I agree with this theoretically but reducing it helps my computer

**Comment by jesse-wei** [comment]
@eric-unc , could you test this latest commit?

I added a startup width/height ratio and the default values are 0.65 and 0.6 (for your computer). Also, let me know if you see our logo for the window icon at the top left and in your dock at the bottom.

**Comment by jesse-wei** [comment]
Startup 0.65 and 0.6 looks like this on mine (so I suspect it may have to be increased for you...)
image

**Comment by eric-unc** [comment]
Sure. Remains at the top. Never been on the bottom.
image

**Comment by jesse-wei** [comment]
Looks like this in the macOS dock (whereas macOS doesn't show window icon)
image

**Comment by eric-unc** [comment]
Yeah, no such blessings on Windows

**Comment by jesse-wei** [comment]
This is good to merge, I'm just playing around with the application name in the dock now

**Pull request merged**
