### PR TITLE
Fix #42, show app icon in Windows dock

### LINKED ISSUE #42: Resizing window bugged
https://user-images.githubusercontent.com/69875698/230701432-d2f5bfc2-d311-4e24-a935-518184a32173.mov

Once the image expands, it doesn't seem to want to shrink. This bug is caused by commit 89a0c58. Couldn't test with certainty on commit f43156d since I couldn't change my window size much on that commit, but I'm 99.9% sure the problem is 89a0c58.

### PR DESCRIPTION
**Pull request by jesse-wei**
Also changed `gui.py` to `gui`. You would now run with `./gui` (macOS/Linux) or `python gui` (a bit weird, but saw this might help with showing an app name in the macOS dock?).

### CODE REVIEW

**Comment by eric-unc** [comment]
Taking out the `.py` is cursed, but I can see the bottom HCT logo on my computer.

**Comment by jesse-wei** [comment]
> Taking out the `.py` is cursed, but I can see the bottom HCT logo on my computer.

Thanks for testing.

I'll change it back to `gui.py` in a few days if it doesn't seem to work. For now, just want to test with it in case it does affect something.

**Comment by jesse-wei** [comment]
Nvm that's dumb, I'll keep it as `gui` (no .py) in my personal branch.

**Comment by jesse-wei** [comment]
Not gonna merge yet because of https://github.com/COMP523TeamD/HeadCircumferenceTool/issues/42.

**Comment by jesse-wei** [comment]
@eric-unc , one last check, does this new startup size still look fine on your laptop?

**Comment by eric-unc** [comment]
No.
image

**Review by eric-unc — CHANGES_REQUESTED** [review]
Worse

**Comment by jesse-wei** [comment]
Well, it seems to be caused by setting min size to (1, 1), which is necessary to prevent the resizing bug. Try tweaking min size (which can't be 0, 0) and startup ratios?

**Comment by eric-unc** [comment]
k

**Comment by jesse-wei** [comment]
How does .65 and .6 look fine on yours?

**Comment by eric-unc** [comment]
Good that's why I pushed it :P

**Comment by jesse-wei** [comment]
0.65 and 0.6 looks like this on mine

image

If no setting looks fine on both our laptops, we should perhaps get rid of some spacers in the `.ui` file.

**Comment by jesse-wei** [comment]
Got rid of the spacers above the two previous buttons and it now looks fine on startup
image

**Comment by jesse-wei** [comment]
Alright, hopefully that's the final (final) change. If it looks fine on yours, this should be merged.

**Comment by jesse-wei** [comment]
Gonna assume it looks fine on yours since removing spacers wouldn't break it.

**Comment by eric-unc** [comment]
Yeah looks fine

**Pull request merged**
