### PR TITLE
NeuroRuler rename

### PR DESCRIPTION
**Pull request by eric-unc**
NogginMeter was a better name tbh

### CODE REVIEW

**Comment by eric-unc** [comment]
Need to actually move/rename the name of the repo for this to be complete, but maybe that could be separate.

**Comment by jesse-wei** [comment]
> NogginMeter was a better name tbh

L + ratio

**Review by jesse-wei — APPROVED** [review]

**Comment by eric-unc** [comment]
this PR is definitely an L

**Comment by jesse-wei** [comment]
We'll rename the repo and directory names after confirming with Prof. Styner

**Pull request merged**
