### PR TITLE
pre-commit recommendations

### PR DESCRIPTION
**Pull request by eric-unc**
be careful what you wish for

### CODE REVIEW

**Comment by eric-unc** [comment]
There's probably a way to get pre-commit (or black) to ignore certain files. Though perhaps if `ui_mainwindow.py` is generated as a result of compilation then it shouldn't be in the repo anyway.

**Comment by jesse-wei** [comment]
> There's probably a way to get pre-commit (or black) to ignore certain files. Though perhaps if `ui_mainwindow.py` is generated as a result of compilation then it shouldn't be in the repo anyway.

Yes, this file should not be autoformatted. However, it should be in the repo because if someone made a change and recompiled, everyone else should pull it.

**Review by jesse-wei — APPROVED** [review]
Just excluded `ui_mainwindow.py|stylesheet.qss|resources.py` from pre-commit actions. Don't name any non-generated files these names.

**Review by COMP523TeamD — APPROVED** [review]
Good changes, Eric and Jesse!

**Comment by jesse-wei** [comment]
> Good changes, Eric and Jesse!

np, Jesse.

**Pull request merged**
